services:
  - type: web
    name: my-cl-generator-api
    env: python3
    buildCommand: pip install -r backend/requirements.txt && python -m spacy download en_core_web_sm
    startCommand: cd backend && python app.py
    envVars:
      - key: PORT
        value: 5000
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://my-cl-generator-macjacker.vercel.app,https://my-cl-generator.vercel.app 